export const myNFTsData = [
  {
    img: "https://preview.colorlib.com/theme/photosen/images/nature_small_9.jpg.webp",
    categ: "Nature",
    price: 23,
    Name: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    Desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    seller: "i am seller :)",
    islisted: true,
  },
  {
    img: "https://preview.colorlib.com/theme/photosen/images/nature_small_8.jpg.webp",
    categ: "Architecture",
    price: 23,
    Name: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    Desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    seller: "i am seller :)",
    islisted: false,
  },
  {
    img: "https://preview.colorlib.com/theme/photosen/images/nature_small_7.jpg.webp",
    categ: "People",
    price: 23,
    Name: "Lorem Ipsum is simply dummy text of the printing",
    Desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    seller: "i am seller :)",
    islisted: true,
  },
  {
    img: "https://preview.colorlib.com/theme/photosen/images/nature_small_6.jpg.webp",
    categ: "Travel",
    price: 23,
    Name: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    Desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    seller: "i am seller :)",
    islisted: true,
  },
  {
    img: "https://preview.colorlib.com/theme/photosen/images/nature_small_5.jpg.webp",
    categ: "Sport",
    price: 23,
    Name: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    Desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    seller: "i am seller :)",
    islisted: false,
  },
  {
    img: "https://preview.colorlib.com/theme/photosen/images/nature_small_4.jpg.webp",
    categ: "Portrait",
    price: 23,
    Name: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    Desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    seller: "i am seller :)",
    islisted: true,
  },
  {
    img: "https://preview.colorlib.com/theme/photosen/images/nature_small_1.jpg.webp",
    categ: "Portrait",
    price: 23,
    Name: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    Desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    seller: "i am seller :)",
    islisted: true,
  },
  {
    img: "https://preview.colorlib.com/theme/photosen/images/nature_small_3.jpg.webp",
    categ: "Portrait",
    price: 23,
    Name: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    Desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    seller: "i am seller :)",
    islisted: true,
  },
];
